### ISSUE TITLE
SoundNet Transfer Code

### ISSUE THREAD

**Issue by hackerekcah** [MaigoAkisame/cmu-thesis#2]
Great work!
How can I get your pytorch version of the SoundNet code and the pretrained model of your phd thesis?

**Comment by MaigoAkisame** [comment]
Hi! Could you send me an email at maigoakisame at gmail dot com?

I can send you a copy of the code. But it's a long time since I looked at the code, so it won't run directly, and you may need to cherry-pick parts of it to make it work.

I have too many model files lying around, so I'm afraid I won't have the time to find out which I used in my thesis...

**Comment by hackerekcah** [comment]
Email sent.
